# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tcp_client_list.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'tcp_client_list.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tcp_client_list.proto\"\x9a\x01\n\rTcpClientInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\x07\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61pp_version\x18\x03 \x01(\t\x12\x16\n\x0e\x63onfig_version\x18\x04 \x01(\t\x12\x13\n\x0b\x63onfig_hash\x18\x05 \x01(\t\x12\x12\n\nnode_alias\x18\x06 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x01(\t\"0\n\rTcpClientList\x12\x1f\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x0e.TcpClientInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tcp_client_list_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TCPCLIENTINFO']._serialized_start=26
  _globals['_TCPCLIENTINFO']._serialized_end=180
  _globals['_TCPCLIENTLIST']._serialized_start=182
  _globals['_TCPCLIENTLIST']._serialized_end=230
# @@protoc_insertion_point(module_scope)
